### ISSUE TITLE
portscanning network

### ISSUE THREAD

**Issue by ruangnode** [covalenthq/rudder#140]
why is the node software passing private IP address to remote machines?
> ##########################################################################
> #               Netscan detected from host   65.X.X.X           #
> ##########################################################################
>
> time                protocol src_ip src_port          dest_ip dest_port
> ---------------------------------------------------------------------------
> Thu Jul 13 18:30:16 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539
> Thu Jul 13 18:30:46 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539
> Thu Jul 13 18:30:55 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539
> Thu Jul 13 18:31:49 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539
> Thu Jul 13 18:32:27 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539
> Thu Jul 13 18:34:24 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539

**Comment by noslav** [comment]
> why is the node software passing private IP address to remote machines?
> 
> > ##########################################################################
> > # Netscan detected from host   65.X.X.X
> > ##########################################################################
> > ## time                protocol src_ip src_port          dest_ip dest_port
> > Thu Jul 13 18:30:16 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539
> > Thu Jul 13 18:30:46 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539
> > Thu Jul 13 18:30:55 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539
> > Thu Jul 13 18:31:49 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539
> > Thu Jul 13 18:32:27 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539
> > Thu Jul 13 18:34:24 2023 TCP   65.X.X.X 4001  =>      10.X.X.X 28539

Please refer to `ipfs` issue and try the solution recommended in https://github.com/ipfs/kubo/issues/4343
